### ISSUE TITLE
Handling File-related Exceptions in OutputComparer

### ISSUE THREAD

**Issue by sandders** [Eto322/Lab1EuDiffusion#2]
https://github.com/Eto322/Lab1EuDiffusion/blob/5a42a7eb55bf557f9fc2fa41bb62254baa19c6ef/OutputComparer.cs#L22

he OutputComparer class in the provided code performs file operations, such as reading from files using File.ReadAllText and creating files using File.Create. However, the class does not handle any file-related exceptions that may occur during these operations. This can lead to unexpected errors and crashes if there are issues with file access, permissions, or other file-related problems.

Proposed Solution:
It is recommended to handle file-related exceptions in the OutputComparer class to ensure robustness and graceful error handling. Specifically, the following actions can be taken:

1. Surround file read operations in the ReadFromFile method with a try-catch block to catch and handle any IOException or UnauthorizedAccessException that may occur.
2. Handle the scenario when creating a file in the ReadFromFile method by checking if the file already exists before attempting to create it. If the file does not exist and an exception is thrown during the creation, handle the exception and provide appropriate error handling or feedback to the caller.
3. Consider logging or displaying meaningful error messages when exceptions occur, to aid in troubleshooting and debugging.

By implementing these changes, the OutputComparer class will be more resilient to file-related issues and provide a more reliable and user-friendly experience when comparing output files.

**Comment by Eto322** [comment]
done as https://github.com/Eto322/Lab1EuDiffusion/commit/927e8cbf9538410099597eac1b7c9f8cb8d9f6a5

**Comment by sandders** [comment]
Issue resolved 😘
