### ISSUE TITLE
Magic numbers

### ISSUE THREAD

**Issue by IanaKhitsko** [Eto322/Lab1EuDiffusion#3]
https://github.com/Eto322/Lab1EuDiffusion/blob/927e8cbf9538410099597eac1b7c9f8cb8d9f6a5/CoinWorker.cs#L22

Please make these magic numbers as consts and check the initial numbers in the task

**Comment by Eto322** [comment]
fixed as https://github.com/Eto322/Lab1EuDiffusion/commit/4329b7e9b029970145a7a9a69642c5d303adf7fa
Now we have a proper const for this . 
https://github.com/Eto322/Lab1EuDiffusion/blob/4329b7e9b029970145a7a9a69642c5d303adf7fa/CoinWorker.cs#L7

https://github.com/Eto322/Lab1EuDiffusion/blob/4329b7e9b029970145a7a9a69642c5d303adf7fa/CoinWorker.cs#L27-L28
