### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by IanaKhitsko** [Eto322/Lab1EuDiffusion#4]
https://github.com/Eto322/Lab1EuDiffusion/blob/927e8cbf9538410099597eac1b7c9f8cb8d9f6a5/CoinWorker.cs#L25C27-L25C28

Also add a check for negative values and than xl < xh, yl<yh

**Comment by Eto322** [comment]
done as https://github.com/Eto322/Lab1EuDiffusion/commit/2e0c67141eae809d938a00c6555cd59345827922
Now its look like this 
https://github.com/Eto322/Lab1EuDiffusion/blob/2e0c67141eae809d938a00c6555cd59345827922/CoinWorker.cs#L25-L35

In this updated code, I added additional conditions to check if any of the coordinates (xl, yl, xh, yh) are less than zero.If any of these conditions are not met, it will throw an exception with the message.
