### ISSUE TITLE
Another magic numbers

### ISSUE THREAD

**Issue by IanaKhitsko** [Eto322/Lab1EuDiffusion#5]
https://github.com/Eto322/Lab1EuDiffusion/blob/927e8cbf9538410099597eac1b7c9f8cb8d9f6a5/CoinWorker.cs#L42

Please make it const. The same for 1000

**Comment by Eto322** [comment]
fixerd as https://github.com/Eto322/Lab1EuDiffusion/commit/4329b7e9b029970145a7a9a69642c5d303adf7fa

now we have a proper consts for this 
https://github.com/Eto322/Lab1EuDiffusion/blob/4329b7e9b029970145a7a9a69642c5d303adf7fa/CoinWorker.cs#L8-L10

https://github.com/Eto322/Lab1EuDiffusion/blob/4329b7e9b029970145a7a9a69642c5d303adf7fa/CoinWorker.cs#L56

https://github.com/Eto322/Lab1EuDiffusion/blob/4329b7e9b029970145a7a9a69642c5d303adf7fa/CoinWorker.cs#L69
