### ISSUE TITLE
Countries number 

### ISSUE THREAD

**Issue by IanaKhitsko** [Eto322/Lab1EuDiffusion#6]
https://github.com/Eto322/Lab1EuDiffusion/blob/927e8cbf9538410099597eac1b7c9f8cb8d9f6a5/DiffusionWorker.cs#L12

44 - that is true, but there is another country number in the task (for the map of 10x10)

**Comment by Eto322** [comment]
fixed as https://github.com/Eto322/Lab1EuDiffusion/commit/4329b7e9b029970145a7a9a69642c5d303adf7fa
Now its corresponds to the data in the task
https://github.com/Eto322/Lab1EuDiffusion/blob/4329b7e9b029970145a7a9a69642c5d303adf7fa/DiffusionWorker.cs#L12

> The country description has the format: name xl yl xh yh, where name is a single word with at most 25 characters;
